name: peckish_animated_hand_tutorial
description: A package to guide users through tutorials with animated hands.
version: 1.0.0
homepage: https://github.com/alokjha2/peckish_animated_hand_tutorial
repository: https://github.com/alokjha2/peckish_animated_hand_tutorial
issue_tracker: https://github.com/alokjha2/peckish_animated_hand_tutorial/issues

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
  - assets/
